### ISSUE TITLE
Generate code for JSON serialization

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/sonde-go#5]
It would help clients dealing with fat firehoses that need to treat JSON data if sonde-go provided "fast" JSON marshaling (and optionally unmarshalling) of the firehose messages.

**Comment by ahevenor** [comment]
@CAFxX can you add some more details to this request. Were not sure what you are looking to accomplish.

**Comment by CAFxX** [comment]
@ahevenor generating easyjson marshalers and unmarshalers (similarly to the way the protobuf marshalers and unmarshalers are generated)

**Comment by ahevenor** [comment]
@CAFxX we reviewed this in our weekly planning and see the value but didn't have enough experience with easyjson to take this on. I am going to close for now but PR's welcome for this functionality.
